### ISSUE TITLE
[Feature Request] Sentry support

### ISSUE THREAD

**Issue by nrobi144** [touchlab/CrashKiOS#19]
I can see the [Sentry branch](https://github.com/touchlab/CrashKiOS/tree/kpg/sentry), which is probably dropped.

Would be good to know what the [Sentry](https://sentry.io/) integration status is, what steps are needed to make it work and if any blockers (Sentry API, etc...). 
Happy to contribute

**Comment by AshStefanOltmann** [comment]
Yes, please support Sentry!

**Comment by kpgalligan** [comment]
Supproted in Kermit: https://github.com/touchlab/Kermit/tree/main/kermit-sentry. If you want it without "kermit", just copy Kermit's implementation.

**Comment by kaushalyap** [comment]
@kpgalligan I cannot see Sentry support, seems it was removed, any plan to add it back?

**Comment by kpgalligan** [comment]
We were waiting on the official sentry library. They've been working on it for a while but still haven't released it.

https://github.com/getsentry/sentry-kotlin-multiplatform

NSExceptionKt supports sentry, although I haven't tried sentry support with it. https://github.com/rickclephas/NSExceptionKt

We may look into adding it, or publishing a fork of the official sentry one.

**Comment by dees91** [comment]
> We were waiting on the official sentry library. They've been working on it for a while but still haven't released it.
> 
> https://github.com/getsentry/sentry-kotlin-multiplatform

Looks like the official sentry library is available now, will you plan to add sentry integration?

**Comment by dees91** [comment]
Ignore my question, looks like they incorporated NSException on their own:
https://github.com/getsentry/sentry-kotlin-multiplatform/blob/main/sentry-kotlin-multiplatform/src/appleMain/kotlin/io/sentry/kotlin/multiplatform/nsexception/NSException.kt

**Comment by kpgalligan** [comment]
CrashKiOS needs a redesign, as some of the core original design was intended to work around some linking issues. Those linking issues are actually worse, so we need a different approach. Crashlytics support is now all dynamic Objc calls, but Bugsnag can't do that, so we need something else.

Sentry has 1st party support, but the same linking issues. I've chatted with them about that. If we come up with anything that would work well for them, we'll maybe do a PR or at least a "head's up".

However, since they have a 1st party implementation, I'm not sure we'd ever add Sentry back into CrashKiOS. No point.
